Update/adds supabase integration
phivk/gradu.al pull request #126
Opened 2022-05-27 12:33 UTC by doingandlearning

This adds the Supabase integration into the project. It also adds the store and function to trigger the data fetch if it hasn't happened already.

To test, you'll need the Supabase key and url to add into the `.env` file - I'll share these over Slack.

1. Run `yarn install`
2. Navigate to the route page and confirm everything works as expected (nothing is broken)
3. Make a newline between the opening div and the SocialHead component in CommunityPage.vue and add `{{ JSON.stringify(supabase.topics) }}` or something similar. 
4. View on the frontend and confirm that the data is present.

In my testing branch, you can see how this would work with the Graph and List component (https://github.com/phivk/gradu.al/blob/temp/experimenting-with-forms/pages/viz.vue). There's a weird thing where spreading in a new array `[...array]` is still being treated as a Vuex object - yuck! So, for now I've got a horrible use of JSON.stringify and JSON.parse to make this work :)

2022-06-24 18:39 UTC, phivk reviewed
finally got to review this 😅 

It works! Initially I was getting CORS errors, which was confusing as actually the issue seems to be that the SupaBase project was paused. When I restored the project, everything worked.

I tried the suggested `{{ JSON.stringify(supabase.topics) }}` and it works.
I also tried `{{ supabase.topics }}`, which also works.

This make me ask two questions:

1. Are you sure the Stringify hack is necessary?
2. Will you fix it as part of this PR or do you prefer to save it for later? On first sight it seems like this is such a common usecase that we should be able to figure this out, but let me know your thoughts 😉

2022-06-26 19:07 UTC, doingandlearning commented
> This make me ask two questions:
> 
> 1. Are you sure the Stringify hack is necessary?

The issue is that we're logging the whole of the object here which is why we are stringifying. Normally, we'd use a `v-for` or access a particular key. This is merely to demonstrate that the data is getting from Supabase to the page.

> 2. Will you fix it as part of this PR or do you prefer to save it for later? On first sight it seems like this is such a common usecase that we should be able to figure this out, but let me know your thoughts 😉

I think the above comment addresses this - this PR was about getting the data from Supabase to the app and the stringify was to demonstrate that is true. Going forward we don't need to stringify because we've accessing the actual data we want. 

Hope that answers your questions :)

2022-07-08 15:12 UTC, phivk commented
@doingandlearning 
I've had a closer look and will leave some more detailed review comments.

On a general note, I would like to change the base brach of the three PRs to https://github.com/phivk/gradu.al/tree/supabase-integration so we can work on the styling, integration and any other further development separately from `develop`.

2022-07-08 15:58 UTC, phivk requested changes

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +      _cssClass: "Member",
the createNodes function prepares the graph data structure specifically as expected by the `vue-d3-network` lib, and thus sets a lot of display attributes like `_cssClass` and `_svgAttrs`. 
I think this should not be the responsibility of the store and therefore this function could better be defined in an external utility file.

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +function createNodes(members, topics, mappings) {
this function create a graph, made up from Nodes and Edges, specifically targeting `vue-d3-network`. Could that be reflected in the function name? 
`createVueD3NetworkGraph()`?
`createNodesEdgesForVueD3Network()`?
...?

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +      .from("members_topics")
why call it `mapping` here and `members_topics` in SupaBase?
Let's make it consistent.

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +      .from("members_topics")
also `mapping` is singluar here, but `mappings` is plural in the `createNodes()` signature, which is confusing

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +  for (const topic of mappings.filter((item) => item.learner)) {
It takes me quite some time to wrap my head around how this loop is adding learning relationships to the edges array. Perhaps add a little comment that describes what the function is doing?

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +    counter.learners[`topic-${topic.topic}`].count++;
we used to keep track of `sharerCount` and `learnerCount` in https://github.com/phivk/gradu.al/blob/1b34d7f61c10962ab7625b0f467305dd39db308c/fetchData.js#L137

I guess you are proposing a slight refactor of the nodes edges data structure?
Please note that `components/MostPopularSkillsSection.vue` is relying on `skill.learnerCount`
see https://github.com/phivk/gradu.al/blob/1b34d7f61c10962ab7625b0f467305dd39db308c/components/MostPopularSkillsSection.vue#L44

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +  for (const share of mappings.filter((item) => item.sharer)) {
maybe another comment here to describe what this function is doing?

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +    counter.learners[`topic-${topic.topic}`].count++;
oh, now I see that you're mapping this below...
I guess it is efficient to do the counting while iterating over the edges, but it makes the function hard to parse for me as a human. Not sure about the best approach here.

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +    nodes.push(topicToUpdate);
could this be simpler via
```
nodes[indexToReplace] = topicToUpdate
```
?

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +  for (const [topic, detail] of Object.entries(counter.learners)) {
another documentation comment would be nice here.

2022-07-08 15:58 UTC, phivk commented on store/supabase.js
> +  for (const [topic, detail] of Object.entries(counter.sharers)) {
and a documentation comment here :)

2022-08-07 18:47 UTC, doingandlearning commented
I've updated this branch based on our previous discussions.

2022-08-08 12:35 UTC, phivk approved these changes

2022-08-08 12:35 UTC, merged