Update/refactos viz to supabase
phivk/gradu.al pull request #128
Opened 2022-05-28 12:53 UTC by doingandlearning

Note: This depends on #126 and so will need to rebased if there are any changes to that branch

To test:
- Navigate to the index page
- Confirm that the Graph and List view are both displaying the test data from the Supabase instance.

2022-07-22 15:01 UTC, phivk requested changes
looks good, one minor change request

2022-07-22 15:01 UTC, phivk commented on components/IntentionSection.vue
> +      return this.nodes.filter(item => item["_cssClass"] === "Skill")
in the current implementation skills are sorted based on learnerCount + sharerCount during the fetch process (see fetchData.js). From a UX perspective it is important that this sorting stays in place. I think it could happen here as part of the computed() property definition.

2022-07-22 15:01 UTC, phivk commented on components/IntentionSection.vue
> +      return JSON.parse(JSON.stringify(this.$store.state.supabase.nodes))
can you help me understand why we need to stringify and parse?

2022-08-07 19:56 UTC, doingandlearning commented on components/IntentionSection.vue
> +      return this.nodes.filter(item => item["_cssClass"] === "Skill")
Yeah - that's resolved now :) Added a custom sort function to handle the logic.

2022-08-08 13:07 UTC, phivk approved these changes

2022-08-08 13:07 UTC, merged