Update/meta descriptors
phivk/gradu.al pull request #49
Opened 2021-03-12 14:37 UTC by doingandlearning

Adds Social Meta descriptors to each page.

2021-03-12 19:26 UTC, phivk commented
@doingandlearning if I test a session page the meta description shows the general Gradual description:
https://www.heymeta.com/url/gradual-git-update-meta-descriptors-phivk.vercel.app/mozfest/sessions/how-to-foster-healthy-online-communities

I think the field on `$content` based `session` might be called different...

2021-03-12 19:29 UTC, phivk requested changes
if I test a session page the meta description shows the general Gradual description instead of the sessions 'summary' above the `<-- more -->` fold:
https://www.heymeta.com/url/gradual-git-update-meta-descriptors-phivk.vercel.app/mozfest/sessions/how-to-foster-healthy-online-communities

I think the field on `$content` based `session` might be called different...

2021-03-13 15:16 UTC, doingandlearning commented
Ah -  I wasn't setting the top level description, just the socials. 

Ready for testing again @phivk

2021-03-13 22:08 UTC, phivk requested changes
see code comments.

Generally, I am not so sure about setting head tags in de body of a component. I suspect there is a more elegant JS based solution that doesn't touch component templates.
But let's leave that as a post MozFest exercise :)

2021-03-13 22:08 UTC, phivk commented on components/SocialHead.vue
> +      required: true
why not a default value here?

2021-03-13 22:08 UTC, phivk commented on components/SocialHead.vue
> +      required: true
why not a default value here?

2021-03-13 22:08 UTC, phivk commented on pages/mozfest/index.vue
> +     description=""
leaving this empty results in empty twitter and og descriptions. Perhaps use a default value in SocialHead for the title and description props?

```
<meta data-n-head="ssr" data-hid="twitter:description" name="twitter:description" content="">
<meta data-n-head="ssr" data-hid="og:description" property="og:description" content="">
```
view-source:https://gradual-qpbwuzrfd-phivk.vercel.app/mozfest/

similar for other uses of SocialHead component

2021-03-15 09:09 UTC, doingandlearning commented
Good edge case discerning - I think this approach is probably best. Provide the defaults in nuxt.config.js and then overwrite if there is content to do so.

2021-03-15 10:10 UTC, phivk approved these changes

2021-03-15 10:10 UTC, merged