Feature/graph embed
phivk/gradu.al pull request #9
Opened 2021-02-24 12:45 UTC by doingandlearning

To test:
- Visit /storytellersunited/test 
- Test functionality of the GraphManual component

This may need some more work in terms of mobile interaction. Happy for some input on that :)

2021-02-28 22:08 UTC, phivk requested changes
this d3 wrapper is a great find!
great approach to load the data via 2 json files 👍 

### display issue

the `svg.net-svg` element has a fixed width of 942 px.
On wide screens it doesn't span the full width of the container element, causing some labels to be cut off (see right side):

<img width="1223" alt="964F56DB-4685-4963-8B7D-26A0C59C2F94-577-0000F6EC7DBAA64A" src="https://user-images.githubusercontent.com/902958/109434658-ac172800-7a16-11eb-9709-8b51dfe20ea3.png">

On narrow screens it overflows horizontally, causeing labels to extend beyond the container element:
<img width="997" alt="1A38C052-EDD8-4811-A2CE-02EA9CCE9BDB-577-0000F729B98334D5" src="https://user-images.githubusercontent.com/902958/109434805-49725c00-7a17-11eb-8f20-9914cdb31fed.png">

### Re mobile behaviour: let's not bite off more than we can chew. 

Let's keep in mind that the current Graph Commons implementation also doesn't have perfect behaviour on mobile. Just saying this to note that there's no way we'll implement a perfect mobile solution of this graph view during the 'current sprint'.

The goal for now is to create a view for users that makes sense. To this end I think we are better off showing another kind of view than the graph, rather than trying to fix the mobile behaviour of the graph view.

My proposal would be to show a ordered list of 'top skills'. The first naive implementation could simply use a frequency count of the `nodes`, pick the top 10 skills and display their title and frequency. 

As follow up steps we could add learners/sharers names to the list items.
Later on we could allow users on wider (non-touch) screens to switch between graph and list view (e.g. using tabs).

2021-03-07 13:32 UTC, doingandlearning commented
Hadn't realised there were comments on this PR til now. 👀

2021-03-07 13:34 UTC, doingandlearning commented
> this d3 wrapper is a great find!
> great approach to load the data via 2 json files 👍
> 
> ### display issue
> the `svg.net-svg` element has a fixed width of 942 px.
> On wide screens it doesn't span the full width of the container element, causing some labels to be cut off (see right side):
> 
> <img alt="964F56DB-4685-4963-8B7D-26A0C59C2F94-577-0000F6EC7DBAA64A" width="1223" src="https://user-images.githubusercontent.com/902958/109434658-ac172800-7a16-11eb-9709-8b51dfe20ea3.png">
> 
> On narrow screens it overflows horizontally, causeing labels to extend beyond the container element:
> <img alt="1A38C052-EDD8-4811-A2CE-02EA9CCE9BDB-577-0000F729B98334D5" width="997" src="https://user-images.githubusercontent.com/902958/109434805-49725c00-7a17-11eb-8f20-9914cdb31fed.png">
> 
> ### Re mobile behaviour: let's not bite off more than we can chew.
> Let's keep in mind that the current Graph Commons implementation also doesn't have perfect behaviour on mobile. Just saying this to note that there's no way we'll implement a perfect mobile solution of this graph view during the 'current sprint'.
> 
> The goal for now is to create a view for users that makes sense. To this end I think we are better off showing another kind of view than the graph, rather than trying to fix the mobile behaviour of the graph view.
> 
> My proposal would be to show a ordered list of 'top skills'. The first naive implementation could simply use a frequency count of the `nodes`, pick the top 10 skills and display their title and frequency.
> 
> As follow up steps we could add learners/sharers names to the list items.
> Later on we could allow users on wider (non-touch) screens to switch between graph and list view (e.g. using tabs).

2021-03-07 13:35 UTC, doingandlearning commented on components/GraphManual.vue
> +    lcb (link) {
This function is adding the arrow to the edge pointing towards the node.

2021-03-07 13:43 UTC, doingandlearning commented
I think the resizing issue is how the library is initialising - if you refresh at each of those responsive sizes then it seems to do manage full width.

2021-03-07 13:44 UTC, doingandlearning commented on components/GraphManual.vue
> +      this.width = window.width;
It was an attempt to get the view to reinitialise on resize - but didn't work. This is left over code from that - I'll remove it.

2021-03-07 15:43 UTC, merged